apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-external
  name: custom-external
spec:
  replicas: 3
  selector:
    matchLabels:
      app: custom-external
  strategy: {}
  template:
    metadata:
      labels:
        app: custom-external
    spec:
      containers:
      - image: ajay185/frontend:v1.0.0
        name: custom-external
        imagePullPolicy: "Always"
        env:
        - name: SERVER
          value: "http://custom-internal"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
status: {}
