apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: customapp
  labels:
    app: custom-internal
  name: custom-internal
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: custom-internal
  strategy: {}
  template:
    metadata:
      labels:
        app: custom-internal
    spec:
      containers:
      - image: ajay185/backend:v1.0.1
        name: custom-internal
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
status: {}
